In [74]:
#1 importing libraries
import matplotlib.pyplot as plt
import numpy
import pandas
import seaborn
import re

In [75]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [76]:
#2 loading the dataset .csv files using the pandas dataframe
data  = pandas.read_csv("/content/drive/My Drive/Colab Notebooks/data/the-hello-dataset-fa22.csv")
print(data)

                        Name  Gender  HSSC-1  HSSC-2  CGPA FavoriteColor  \
0             Muhammad Usman    Male     440     369  2.80         Black
1                Taha Ishfaq    Male     415     408  2.73           Red
2            Muhammad Hamdan    Male     388     321  2.78         Black
3        Syeda Maham Gillani  Female     412     440  3.11          Blue
4                 Umar Wasim    Male     364     469  2.42         black
..                       ...     ...     ...     ...   ...           ...
129  Muhammad Abubakar Malik    Male     410     349  2.94          Blue
130             Muhammad Ali    Male     403     390  2.52        Yellow
131             Shafaqat Ali    Male     424     400  3.07         Black
132              Ammar Asif     Male     351     423  2.52         Black
133          Muhammad Zubair    Male     361     335  2.81         Black

    BirthMonth  Weight
0        March    77.0
1        March    72.0
2      October    53.0
3     February    63.0
4     October     80.0
..         ...     ...
129   Feburary    65.0
130    October    81.0
131        May    58.0
132  December     68.0
133      March    58.0

[134 rows x 8 columns]

In [77]:
namewithH = data[data.Name.str.contains('^H')]
print(namewithH)

#Var= df[df.Name.str.contains(^H)]

                    Name  Gender  HSSC-1  HSSC-2  CGPA FavoriteColor  \
9           Hamza Naveed    Male     954     459  2.80          Blue
21           Habib Ullah    Male     399     434  3.35       Mustard
22          Hunain Javed    Male     362     413  2.94         Black
58  Hafiz Malahim Labib.    Male     390     430  3.24        Orange
60   Hamna Tariq Saleemi  Female     400     418  2.80         Black
77                  Hina  Female     410     350  2.90          Blue
78      Hamza Javed Khan    Male     400     381  3.39          Blue
80        Husnain Ahmed     Male     335     427  2.41     Dark blue
93      Hamayoun Masroor    Male     428     428  3.16          Pink
98         Hussain Afzal    Male     415     346  2.87          Blue

    BirthMonth  Weight
9          May    58.0
21       April    60.0
22  September     76.0
58         May    54.0
60     October    62.0
77      August    67.0
78    January     78.0
80   September    72.0
93  September     63.0
98       March    81.0

In [73]:
print("Total number of students who have three words name:")


# threeWordsName  = data[data.Name.str.contains(" "+" ")]
# print(threeWordsName)

Total number of students who have three words name:

TypeError: ignored